zip -d app/libs/Peergos.jar com/google/errorprone/\*
zip -d app/libs/Peergos.jar com/google/common/util/\*
zip -d app/libs/Peergos.jar peergos/server/tests/\*
zip -d app/libs/Peergos.jar kotlin/\*
zip -d app/libs/Peergos.jar kotlinx/\*
zip -d app/libs/Peergos.jar org/intellij/\*
zip -d app/libs/Peergos.jar org/jetbrains/\*
zip -d app/libs/Peergos.jar DebugProbesKt.bin
zip -d app/libs/Peergos.jar META-INF/kotlinx\*
zip -d app/libs/Peergos.jar META-INF/versions/9\*
zip -d app/libs/Peergos.jar org/sqlite/native/Mac/\*
zip -d app/libs/Peergos.jar org/sqlite/native/Windows/\*
zip -d app/libs/Peergos.jar org/sqlite/native/OpenBSD/\*
zip -d app/libs/Peergos.jar org/sqlite/native/Linux/\*
zip -d app/libs/Peergos.jar org/sqlite/native/FreeBSD/\*
zip -d app/libs/Peergos.jar org/sqlite/native/Linux-Musl/\*
zip -d app/libs/Peergos.jar org/jline/nativ/\*
zip -d app/libs/Peergos.jar jni/\*
zip -d app/libs/Peergos.jar META-INF/native/\*
zip -d app/libs/Peergos.jar META-INF/lib/osx_64/\*
zip -d app/libs/Peergos.jar META-INF/lib/windows_64/\*
